export const hotelTypes = [
    'Luxury/Resorts',
    'Boutique',
    'Business',
    'Budget or Economy',
    'Extended Stay',
    'Suite',
    'Resorts',
    'Airport',
    'Bed and Breakfast (B&B)',
    'Hostels',
    'Motel',
    'Spa',
    'Casino',
    'All-Inclusive Resorts',
    'Historic',
    'Floating',
    'Themed',
    'Cruise Ship',
    'Ecotels or Green',
    'Capsule',
];

export const hotelFacilities = [
    'Free Wi-Fi',
    'Swimming Pool',
    'Fitness Center',
    'Restaurant',
    'Room Service',
    'Conference Rooms',
    'Parking',
    '24-Hour Front Desk',
    'Air Conditioning',
    'Safety Deposit Box',
];
